export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const FILTER_PRODUCTS_BY_COLOR = "FILTER_PRODUCTS_BY_COLOR";
export const FILTER_PRODUCTS_BY_SEARCH = "FILTER_PRODUCTS_BY_SEARCH";
export const FETCH_FEATURED_PRODUCTS = "FETCH_FEATURED_PRODUCTS";
export const FETCH_PRODUCTS_AUTOCOMPLETE = "FETCH_PRODUCTS_AUTOCOMPLETE";
